config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
   sessions: 'admins/sessions'
}
root 'home#index'
resources :admins, :comments, :languages
resources :lessons do
   collection do
       get 'search'
   end
end
    

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :lessons, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
     belongs_to :lesson
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :lessons, dependent: :destroy
    has_many :comments, through: :lessons

    validates :name, uniqueness: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  belongs_to :admin
  belongs_to :language
  has_many :comments

end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def index
    @admin = Admin.all
     console
      
end

def show

end

def new

end

def create

end

def edit

end

def update

end

def destroy

end

private

def admins_params
  # will return something that looks like this:
  # {name: '....', :description: '...'}

    params.require(:admin).permit(:f_name, :l_name, :date_of_birth)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
      @comments = Comment.all.order(:created_at)
    end
    
    def new
        @comment = Comment.new
        @lessons = Lesson.all
    end
    
    def show
        lesson = Lesson.find(params[:id])
         @comment = lesson.comment
    end
    
    def create
        Comment.create(comments_params)
        flash[:success]='You have successfully created comment'
        redirect_to root_path
    end
    
    def edit
        
        @comment = Comment.find(params[:id])
        
    end
    
    def update
        comment = Comment.find(params[:id])
        comment.update(comment_params)
         flash[:success]='You have successfully updated comment'
        redirect_to comments_path
    end
    
    def destroy
        Comment.destroy(params[:id])
         flash[:error]='Your Comment is deleted'
         render json: {message: 'comment is destroyed!'}
#        redirect_to comments_path 
    end

private

def comments_params
  # will return something that looks like this:
  # {name: '....', :description: '...'}

    params.require(:comment).permit(:description, :lesson_id, :subject)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @languages=Language.all.order(:created_at)
      @lessons = Lesson.all.order(:created_at)
      @comments = Comment.all.order(:created_at)
      @imgs = ['comments64.png', 'comments65.png', 'comments66.png', 'comments67.png']
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: [:destroy]
def index
  @languages = Language.all
end

def show

end

def new
  @languages = Language.all
  @language = Language.new

end

def create
  language = Language.create(languages_params)
  if language.invalid?
    flash[:error] = "Language already exists, please try another one"
    redirect_to new_language_path
  else
    flash[:success] = "Great, your new language has been created!"
    redirect_to languages_path
  end
end

def edit
  @language = Language.find(params[:id])

end

def update
  language = Language.find(params[:id])

  language.update(languages_params)

  redirect_to languages_path
end

def destroy
  Language.destroy(params[:id])
  redirect_to languages_path
end

private

def languages_params
  # will return something that looks like this:
  # {name: '....', :description: '...'}

    params.require(:language).permit(:name, :description)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def index
    @lessons = Lesson.all
  end

def show
  @lesson = Lesson.find(params[:id])

end

def new
  @lesson = Lesson.new
  @languages = Language.all

end

def create
  admin = current_admin
  # admin.id
  Lesson.create(lessons_params.merge({admin_id: admin.id}))

  redirect_to lessons_path

end

def edit
  @lesson = Lesson.find(params[:id])

end

def update
  lesson = Lesson.find(params[:id])
  lesson.update(lessons_params)

  redirect_to lessons_path

end

def destroy
  Lesson.destroy(params[:id])

  redirect_to lessons_path

end

    def search
      words = params[:search_text].downcase.split()
      search_string = []
      for word in words
          search_string.push("lower(syntax) LIKE ?")
      end
      words = words.map {|w| "%#{w}%"}
      @lessons = Lesson.where(search_string.join(' OR '), *words).all
    end

private

    
def lessons_params
  # will return something that looks like this:
  # {name: '....', description: '...', syntax: '...'} + {admin_id: '...'} = {name: '....', description: '...', syntax: '...', admin_id: '...'}

    params.require(:lesson).permit(:name, :description, :syntax, :language_id)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      type = 'success' if type == 'notice'
      type = 'error'   if type == 'alert'
      text = "<script>toastr.#{type}('#{message}');</script>"
      flash_messages << text.html_safe if message
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/admins/index.html.erb
<div class="container admin_box_shadow">
  <div class="row py-3">
    <div class="col-lg-12">
      <h1 class="admin_font text-center">Admin's Panel</h1>
    </div>
  </div>
  <div>
    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">
        <%= link_to 'Languages Base', languages_path, class:'editNDelete' %>

      </div>
    </div>
    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">
        <%= link_to 'Create A Language', new_language_path, class:'editNDelete' %>
      </div>
    </div>

    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">
        <%= link_to 'Lessons Base', lessons_path, class: 'editNDelete' %>
      </div>
    </div>
    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">
        <%= link_to 'Create A Lesson', new_lesson_path, class:'editNDelete' %>
      </div>
    </div>
    <div class="row mx-auto py-3">
      <div class="col-lg-12 text-center">
        <%= render 'admins/shared/adminlinks' %>
      </div>
    </div>
  </div>
</div>

app/views/admins/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h1>
        Welcome To Coding Buds, The Beginner's Path To Coding</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <h2>Just select a language and off you go! Enjoy various lessons and learn about the history of each language
      </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">
      <%= link_to "Log Out", destroy_admin_session_path, method: :delete %>
    </div>
  </div>
</div>

app/views/admins/shared/_adminlinks.html.erb
<div class="row">
  <div class="col-lg-12">
    <%= link_to 'Admin Home', admins_path, class:'AdminHome' %>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <%= link_to 'Log Out', destroy_admin_session_path, method: :delete, class:'AdminHome' %>
  </div>
</div>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CodingBuds</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= "#{controller_name} #{action_name}" %>">

  <nav class="navbar navbar-light">
  <a href="<%= root_path %>" class="navbar-brand" style="font-family: 'Lobster', cursive; font-size: 50px;" title="Go to Home Page"><i class="fas fa-cog fa-spin"></i>Coding Buds</a>
  <%= form_tag '/lessons/search', method: "GET" do %>
      <%= text_field_tag :search_text, "", class:'searchText' %>
      <%= submit_tag "Search", class:"searchButton btn text-center" %>
  <% end %>


 <!--
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <a href="<= admins_path %>">Search Link</a>
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
-->
</nav>
   <br>
   <%=custom_bootstrap_flash %>

    <%= yield %>
<footer>
    
    <p> &copy; Coding Buds</p>
</footer>

  </body>
</html>