config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
   sessions: 'admins/sessions'
}
root 'home#index'
resources :admins, :comments, :languages
resources :lessons do
   collection do
       get 'search'
   end
end
    

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
    has_many :lessons, dependent: :destroy
    has_many :comments, through: :lessons

    validates :name, uniqueness: true
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: [:destroy]
def index
  @languages = Language.all
end

def show

end

def new
  @languages = Language.all
  @language = Language.new

end

def create
  language = Language.create(languages_params)
  if language.invalid?
    flash[:error] = "Language already exists, please try another one"
    redirect_to new_language_path
  else
    flash[:success] = "Great, your new language has been created!"
    redirect_to languages_path
  end
end

def edit
  @language = Language.find(params[:id])

end

def update
  language = Language.find(params[:id])

  language.update(languages_params)

  redirect_to languages_path
end

def destroy
  Language.destroy(params[:id])
  redirect_to languages_path
end

private

def languages_params
  # will return something that looks like this:
  # {name: '....', :description: '...'}

    params.require(:language).permit(:name, :description)
  end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/edit.html.erb
<div class="container py-5 new_language_container">
  <div class="row">
    <div class="col-lg-12 text-center language_secondary_font">
      <h1>
        Edit Language
      </h1>
    </div>
  </div>

  <%= form_for @language do |f| %>
  <div class="row mx-auto justify-content-center">
    <div class="col-lg-6">
      <%=f.label :name %>
      <%= f.text_field :name, class:'form-control language_input' %>
    </div>
  </div>
  <div class="row mx-auto justify-content-center">
    <div class="col-lg-6">
      <%= f.label :description %>
      <%= f.text_field :description, class:'form-control language_input'%>
    </div>
  </div>

  <div class="row mx-auto justify-content-center">
    <div class="col-lg-12 text-center py-2">
      <%= f.submit 'Edit Language', class:'btn language_btn' %>
    </div>
  </div>

<% end %>

</div>
<div class="row mx-auto">
<div class="col-lg-12 text-center">
  <%= render 'admins/shared/adminlinks' %>
</div>
</div>

app/views/languages/index.html.erb
<div class="container py-5 languages_container">
  <div class="row mx-auto">
    <div class="col-lg-12 text-center py-3 language_head_font">
      <h1>Languages Main Base
      </h1>
    </div>
  </div>

  <% @languages.each do |language| %>
    <div class="row mx-auto">
      <div class="col-lg-12 text-center language_padding">

        <%=language.name %>
      </div>
    </div>
    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">

        <%= language.description %>
      </div>
    </div>
    <div class="row mx-auto py-1 rowHover">
      <div class="col-lg-12 text-center">
        <%= link_to 'Edit Language', edit_language_path(language), class:'editNDelete' %>
        |

        <%= link_to 'Delete Language', language_path(language), method: :delete, class:'editNDelete' %>
      </div>
    </div>
  <% end %>
  <div class="row mx-auto py-1">
    <div class="col-lg-12 text-center">
      <%= render 'admins/shared/adminlinks' %>
    </div>
  </div>

</div>

app/views/languages/new.html.erb
<div class="container new_language_container py-5">
  <div class="row">
    <div class="col-lg-12 text-center language_secondary_font">
      <h1>
        Create A New Language
      </h1>
    </div>
  </div>
  <%= form_for @language do |f| %>
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control language_input' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <%= f.label :description %>
      <%= f.text_field :description, class:'form-control language_input' %>
    </div>
  </div>

  <div class="row mx-auto">
    <div class="col-lg-12 text-center py-2">
      <%=f.submit 'Create New Language', class:'btn language_btn' %>
    </div>

  </div>
<% end %>

</div>