config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    registrations: 'admins/registrations',
   sessions: 'admins/sessions'
}
root 'home#index'
resources :admins, :comments, :languages
resources :lessons do
   collection do
       get 'search'
   end
end
    

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  belongs_to :admin
  belongs_to :language
  has_many :comments

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: [:destroy]

  def index
    @lessons = Lesson.all
  end

def show
  @lesson = Lesson.find(params[:id])

end

def new
  @lesson = Lesson.new
  @languages = Language.all

end

def create
  admin = current_admin
  # admin.id
  Lesson.create(lessons_params.merge({admin_id: admin.id}))

  redirect_to lessons_path

end

def edit
  @lesson = Lesson.find(params[:id])

end

def update
  lesson = Lesson.find(params[:id])
  lesson.update(lessons_params)

  redirect_to lessons_path

end

def destroy
  Lesson.destroy(params[:id])

  redirect_to lessons_path

end

    def search
      words = params[:search_text].downcase.split()
      search_string = []
      for word in words
          search_string.push("lower(syntax) LIKE ?")
      end
      words = words.map {|w| "%#{w}%"}
      @lessons = Lesson.where(search_string.join(' OR '), *words).all
    end

private

    
def lessons_params
  # will return something that looks like this:
  # {name: '....', description: '...', syntax: '...'} + {admin_id: '...'} = {name: '....', description: '...', syntax: '...', admin_id: '...'}

    params.require(:lesson).permit(:name, :description, :syntax, :language_id)
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/edit.html.erb
<div class="container py-5 lessons_container2">
  <div class="row">
    <div class="col-lg-12 text-center lesson_edit_head_font">
      <h1>Edit Lesson
      </h1>
    </div>
  </div>

  <%= form_for @lesson do |f| %>
  <div class="row mx-auto justify-content-center">
    <div class="col-lg-6">
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control lesson_input' %>
    </div>
  </div>
  <div class="row mx-auto justify-content-center">
    <div class="col-lg-6">
      <%= f.label :description %>
      <%= f.text_field :description, class:'form-control lesson_input' %>
    </div>
  </div>
  <div class='row mx-auto justify-content-center'>
    <div class="col-lg-10">
      <%= f.label :syntax %>
      <%= f.text_area :syntax, class:'form-control lesson_input' %>
    </div>
  </div>

  <div class="row mx-auto justify-content-center">
    <div class="col-lg-12 text-center py-2 ">
      <%= f.submit 'Edit Lesson', class:'lesson_btn btn' %>
    </div>
  </div>
<% end %>

<div class="row mx-auto">
  <div class="col-lg-12 text-center">
    <%= render 'admins/shared/adminlinks' %>
  </div>
</div>
</div>

app/views/lessons/index.html.erb
<div class="container py-5 lessons_container">
  <div class="row">
    <div class="col-lg-12 lesson_head_font text-center">
      Lessons Main Base
    </div>
  </div>
  <% @lessons.each do |lesson| %>
    <div class="row mx-auto">
      <div class="col-lg-12 text-center lesson_padding">
        <%= lesson.name %>
      </div>
    </div>
    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">
        <%= lesson.description %>
      </div>
    </div>
    <div class="row mx-auto py-1 justify-content-center">
      <div class="col-lg-8">
        <pre data-enlighter-language="<%=lesson.language.name%>">
      <%= lesson.syntax %>
    </pre>
      </div>
    </div>
    <div class="row mx-auto-py-1">
      <div class="col-lg text-center">
        <%= link_to 'Edit Lesson', edit_lesson_path(lesson), class:'editNDelete' %> |

        <%= link_to 'Delete Lesson', lesson_path(lesson), method: :delete, class:'editNDelete' %>
      </div>
    </div>

  <% end %>
  <div class="row mx-auto py-1">
    <div class="col-lg-12 text-center">
      <%= render 'admins/shared/adminlinks' %>
    </div>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="container lessons_container2">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="lesson_edit_head_font">
        Create A New Lesson
      </h1>
    </div>
  </div>

  <%= form_for @lesson do |f| %>
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <%= f.label :name %>
      <%= f.text_field :name, class:'form-control lesson_input' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <%= f.label :description %>
      <%= f.text_field :description, class:'form-control lesson_input' %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <%= f.label :syntax %>
      <%= f.text_area :syntax, class:'form-control lesson_input' %>
    </div>
  </div>
  <div class="row mx-auto py-1">
    <div class="col-lg-12 text-center">
      <%= f.label :language_id %>
      <%= f.select :language_id, options_for_select(@languages.map {|l|[l.name, l.id]}), {}, { class: 'lesson_select'} %>

  </div>
  <div class="row mx-auto">
    <div class="col-lg-12 text-center">
      <%=f.submit 'Create a Lesson', class:'btn lesson_btn' %>
    </div>
  </div>
<% end %>
</div>

app/views/lessons/search.html.erb
<p class="p_search">These are search results for --- <mark> <%= params[:search_text] %></mark></p>


<div class="container py-5 lessons_container">
  <div class="row">
    <div class="col-lg-12 lesson_head_font text-center">
      Lessons Main
    </div>
  </div>
  <% @lessons.each do |lesson| %>
    <div class="row mx-auto">
      <div class="col-lg-12 text-center lesson_padding"><a href="<%= root_path %>">
          <%= lesson.name %></a>
      </div>
    </div>
    <div class="row mx-auto py-1">
      <div class="col-lg-12 text-center">
        <%= lesson.description %>
      </div>
    </div>

    <pre data-enlighter-language="<%=lesson.language.name %>">
      <%= lesson.syntax %>
    </pre>
    <div class="row mx-auto-py-1">
      <div class="col-lg-12 text-center">

      
      </div>
    </div>
<!--
    <div class="row mx-auto">
      <div class="col-lg-12 text-center">
        <= link_to 'Go to Lesson', lesson_path(lesson), method: :delete %>
      </div>
    </div>
-->

  <% end %>
 
</div>